Repository bluesky3268/fastcamp_board, pull requests merged in 2023-04, with the labels that each got.

#42 Feature/#41 UserAccount 도메인 수정
  src/main/java/com/fastcapmus/board/config/DataRestConfig.java
  src/main/java/com/fastcapmus/board/domain/Article.java
  src/main/java/com/fastcapmus/board/domain/ArticleComment.java
  src/main/java/com/fastcapmus/board/domain/UserAccount.java
  src/main/java/com/fastcapmus/board/dto/UserAccountDto.java
  src/main/java/com/fastcapmus/board/repository/UserAccountRepository.java
  src/main/resources/data.sql
  src/test/java/com/fastcapmus/board/controller/ArticleControllerTest.java
  src/test/java/com/fastcapmus/board/service/ArticleCommentServiceTest.java
  src/test/java/com/fastcapmus/board/service/ArticleServiceTest.java
Labels: enhancement

#44 Feature/#43 view func
  build.gradle
  src/main/java/com/fastcapmus/board/controller/ArticleController.java
  src/main/java/com/fastcapmus/board/domain/constant/FormStatus.java
  src/main/java/com/fastcapmus/board/domain/constant/SearchType.java
  src/main/java/com/fastcapmus/board/dto/ArticleDto.java
  src/main/java/com/fastcapmus/board/dto/request/ArticleRequest.java
  src/main/java/com/fastcapmus/board/service/ArticleService.java
  src/main/resources/templates/articles/detail.th.xml
  src/main/resources/templates/articles/form.html
  src/main/resources/templates/articles/form.th.xml
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/articles/index.th.xml
  src/test/java/com/fastcapmus/board/controller/ArticleControllerTest.java
  src/test/java/com/fastcapmus/board/service/ArticleServiceTest.java
  src/test/java/com/fastcapmus/board/util/FormDataEncoder.java
  src/test/java/com/fastcapmus/board/util/FormDataEncoderTest.java
Labels: enhancement

#47 UserAccountDto 리팩토링
  src/main/java/com/fastcapmus/board/controller/ArticleController.java
  src/main/java/com/fastcapmus/board/dto/UserAccountDto.java
Labels: enhancement

#48 #46 [enhancement] - 게시글 뷰 기능 테스트 코드 추가
  src/test/java/com/fastcapmus/board/controller/ArticleControllerTest.java
Labels: enhancement

#49 게시글 댓글 구현
  src/main/java/com/fastcapmus/board/controller/ArticleCommentController.java
  src/main/java/com/fastcapmus/board/dto/ArticleCommentDto.java
  src/main/java/com/fastcapmus/board/dto/request/ArticleCommentRequest.java
  src/main/java/com/fastcapmus/board/service/ArticleCommentService.java
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/detail.th.xml
  src/test/java/com/fastcapmus/board/controller/ArticleCommentControllerTest.java
  src/test/java/com/fastcapmus/board/service/ArticleCommentServiceTest.java
Labels: enhancement

#50 #31 인증 기능 구현
  build.gradle
  src/main/java/com/fastcapmus/board/config/JpaConfig.java
  src/main/java/com/fastcapmus/board/config/SecurityConfig.java
  src/main/java/com/fastcapmus/board/controller/ArticleCommentController.java
  src/main/java/com/fastcapmus/board/controller/ArticleController.java
  src/main/java/com/fastcapmus/board/dto/response/ArticleCommentResponse.java
  src/main/java/com/fastcapmus/board/dto/response/ArticleWithCommentsResponse.java
  src/main/java/com/fastcapmus/board/dto/security/BoardPrincipal.java
  src/main/java/com/fastcapmus/board/repository/ArticleCommentRepository.java
  src/main/java/com/fastcapmus/board/repository/ArticleRepository.java
  src/main/java/com/fastcapmus/board/repository/UserAccountRepository.java
  src/main/java/com/fastcapmus/board/service/ArticleCommentService.java
  src/main/java/com/fastcapmus/board/service/ArticleService.java
  src/main/resources/data.sql
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/detail.th.xml
  src/main/resources/templates/articles/index.th.xml
  src/main/resources/templates/header.html
  src/main/resources/templates/header.th.xml
  src/test/java/com/fastcapmus/board/config/TestSecurityConfig.java
  src/test/java/com/fastcapmus/board/controller/ArticleCommentControllerTest.java
  src/test/java/com/fastcapmus/board/controller/ArticleControllerTest.java
  src/test/java/com/fastcapmus/board/controller/AuthControllerTest.java
  src/test/java/com/fastcapmus/board/controller/MainControllerTest.java
  src/test/java/com/fastcapmus/board/repository/JpaRepositoryTest.java
  src/test/java/com/fastcapmus/board/service/ArticleCommentServiceTest.java
  src/test/java/com/fastcapmus/board/service/ArticleServiceTest.java
Labels: enhancement

#53 #52 헤로쿠에 배포하기
  Procfile
  build.gradle
  src/main/resources/application.yml
  system.properties
Labels: enhancement

#55 #54 [bug] 헤로쿠 DB 변경
  src/main/resources/application.yml
Labels: bug, enhancement

#56 #54 [bug] 오타 수정
  src/main/resources/application.yml
Labels: bug, enhancement

#57 #54 [bug] 헤로쿠 설정 Procfile
  Procfile
Labels: bug, enhancement

#72 [고도화] usecase 업데이트
  document/usecase.svg
Labels: documentation

#74 #73 [enhancement] 엔티티 리팩토링
  src/main/java/com/fastcapmus/board/domain/Article.java
  src/main/java/com/fastcapmus/board/domain/ArticleComment.java
  src/main/java/com/fastcapmus/board/domain/UserAccount.java
Labels: enhancement
